name: Bun CI

on:
  push:
    branches: ["bun"]
  schedule:
    - cron: "0 0 * * *"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: üçΩÔ∏è Get working copy
        uses: actions/checkout@v3

<<<<<<<< HEAD:.github/workflows/bun.yml
      - name: üéâ Setup Bun runtime
        uses: antongolub/action-setup-bun@v1
========
      - name: üéâ Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          cache: "npm"
>>>>>>>> main:.github/workflows/node.yml

      - name: üß† Caching
        id: cache_node_modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: ‚òÑÔ∏è Install Dependencies
        run: bun install

      - name: üç≥ Make Quote
        run: bun run dev

      - name: üöÄ Deploy
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          echo "today=$(date +%y/%m/%d)" >> $GITHUB_ENV
          git add .
          git commit -m ":fire: updated README.md :memo:"|| echo updated on $today
          git push -f
